### ISSUE TITLE
plots overlayed in a wrong order

### ISSUE THREAD

**Issue by danton267** [plotly/plotly.R#2017]
```

library(plotly)
library(ggplot2)
library(tidyverse)
data <- tibble(
  name = rep("Example", 2),
  group = c("Qualitative", "Measure"),
  value = c(100, 75),
  width = c(0.9, 0.5)
)

p <- data %>% 
  ggplot(aes(x = value, y = name, fill = group)) +
  geom_col(width = data$width) +
  coord_cartesian(ylim = c(0.3, 1.7)) +
  scale_fill_manual(values = c("black", "grey")) +
  theme_minimal() +
  theme(panel.grid.major.y = element_blank())

ggplotly(p)
```
The grey plot covers the black one which is supposed to be on the top.

**Comment by cpsievert** [comment]
I actually find `{ggplot2}`'s behavior here somewhat surprising (i.e., drawing using _reverse_ alpha-numeric ordering) and I'm afraid that changing it now is going to have bad consequences for existing `ggplotly()` code that assumes that things work the way it currently does.

That being said, there is a pretty satisfactory workaround: use `factor()`s instead of `character()`s to control the ordering:

```r
data <- tibble(
  name = rep("Example", 2),
  group = factor(c("Qualitative", "Measure"), c("Qualitative", "Measure")),
  value = c(100, 75),
  width = c(0.9, 0.5)
)
```
